use_frameworks!

target 'QXWIntroController_Example' do
  pod 'QXWIntroController', :path => '../'

  target 'QXWIntroController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
